using System.Text;
using AiAgentChallenge.Application.Abstractions;
using AiAgentChallenge.Domain;

namespace AiAgentChallenge.Infrastructure.Git;

public sealed class PrDescriptionBuilder : IPrDescriptionBuilder
{
    public string Build(ExecutionReport report)
    {
        var finalChangedFiles = GetFinalChangedFiles(report);
        var builder = new StringBuilder();
        builder.AppendLine("## Summary");
        builder.AppendLine(report.AiSummary);
        builder.AppendLine();
        builder.AppendLine("## Task");
        builder.AppendLine(report.TaskId);
        builder.AppendLine();
        builder.AppendLine("## Changes");

        foreach (var file in finalChangedFiles)
        {
            builder.AppendLine($"- {file}");
        }

        builder.AppendLine();
        builder.AppendLine("## Test Result");
        var latestTest = report.TestResults.LastOrDefault();
        builder.AppendLine($"Command: {latestTest?.Command ?? report.RepositoryAnalysis?.TestCommand ?? string.Empty}");
        builder.AppendLine($"Status: {ToDisplayText(report.FinalTestStatus)}");
        if (latestTest is not null && latestTest.Duration > TimeSpan.Zero)
        {
            builder.AppendLine($"Duration: {latestTest.Duration:c}");
        }

        builder.AppendLine();
        builder.AppendLine("## AI Usage");
        builder.AppendLine($"Model: {report.AiModel}");
        builder.AppendLine("Changed files:");

        foreach (var file in finalChangedFiles)
        {
            builder.AppendLine($"- {file}");
        }

        builder.AppendLine();
        builder.AppendLine("## Generated By");
        builder.AppendLine("AI Development Agent");

        return builder.ToString().TrimEnd();
    }

    private static IReadOnlyList<string> GetFinalChangedFiles(ExecutionReport report)
    {
        return report.GitChangedFiles.Count > 0
            ? report.GitChangedFiles
            : report.ChangedFiles;
    }

    private static string ToDisplayText(TestExecutionStatus status)
    {
        return status.ToString();
    }
}
