using AiAgentChallenge.Domain;
using AiAgentChallenge.Infrastructure.Git;

namespace AiAgentChallenge.UnitTests.Infrastructure;

public sealed class PrDescriptionBuilderTests
{
    [Fact]
    public void Build_IncludesExpectedSections()
    {
        var builder = new PrDescriptionBuilder();

        var body = builder.Build(new ExecutionReport
        {
            TaskId = "TASK-123",
            AiSummary = "Added email validation.",
            AiModel = "gpt-4.1",
            GitChangedFiles = new[] { "src/Users/RegisterService.cs", "tests/RegisterServiceTests.cs" },
            TestResults = new[]
            {
                new TestResult
                {
                    Command = "dotnet test",
                    Status = TestExecutionStatus.Passed,
                    Duration = TimeSpan.FromSeconds(1),
                    AttemptNumber = 1
                }
            },
            FinalTestStatus = TestExecutionStatus.Passed
        });

        Assert.Contains("## Summary", body);
        Assert.Contains("## Task", body);
        Assert.Contains("## Changes", body);
        Assert.Contains("## Test Result", body);
        Assert.Contains("## AI Usage", body);
        Assert.Contains("## Generated By", body);
        Assert.Contains("Command: dotnet test", body);
        Assert.Contains("Status: Passed", body);
        Assert.Contains("Duration: 00:00:01", body);
        Assert.Contains("- src/Users/RegisterService.cs", body);
        Assert.Contains("Model: gpt-4.1", body);
    }

    [Fact]
    public void Build_FallsBackToChangedFiles_WhenGitChangedFilesIsEmpty()
    {
        var builder = new PrDescriptionBuilder();

        var body = builder.Build(new ExecutionReport
        {
            TaskId = "TASK-456",
            AiSummary = "Updated files.",
            AiModel = "gpt-4.1-mini",
            ChangedFiles = new[] { "src/File.cs", "tests/FileTests.cs" },
            FinalTestStatus = TestExecutionStatus.Skipped
        });

        Assert.Contains("- src/File.cs", body);
        Assert.Contains("- tests/FileTests.cs", body);
        Assert.DoesNotContain("Duration:", body, StringComparison.Ordinal);
    }
}
